[pis]
pi1 ansible_host=192.168.0.161 role=server
pi2 ansible_host=192.168.0.162 role=worker
pi3 ansible_host=192.168.0.163 role=worker
pi4 ansible_host=192.168.0.164 role=worker

[all:vars]
ansible_user=pi
ansible_ssh_private_key_file=~/.ssh/pi_cluster_key
ansible_python_interpreter=/usr/bin/python3
