---
apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
  namespace: fakestore
data:
  DB_HOST: "postgres"
  SPRING_PROFILES_ACTIVE: "k8s"
  DB_ADMIN_USER: "fakestore_users_admin"
  DB_USER: "fakestore_users_user"
  SERVER_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: fakestore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: ghcr.io/fake-store/fakestore-users:${USERS_TAG}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: users-config
            - secretRef:
                name: users-secret
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: fakestore
spec:
  selector:
    app: users
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
