---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
  namespace: fakestore
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka-0.kafka.fakestore.svc.cluster.local:9092"
  SPRING_PROFILES_ACTIVE: "k8s"
  SERVER_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: fakestore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: ghcr.io/fake-store/fakestore-orders:sha-e7f04b9
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: orders-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: fakestore
spec:
  selector:
    app: orders
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
